kube context for helm

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,5 @@
 #!/bin/sh
 
-set -o pipefail
 set -o errexit
 
 usage() {
@@ -12,13 +11,20 @@ if [ $# != 1 ]; then
   exit 1
 fi
 
+_kctx="$(kubectl config get-contexts --no-headers -o name | grep ${1} | head -n1)"
+
+if [ -z "${_kctx}" ]; then
+  printf "error: cannot find a kube context for cluster ${1}\n"
+  exit 1
+fi
+
 cd resources
 
 terraform init
 terraform workspace new "${1}" || terraform workspace select "${1}"
 terraform apply -auto-approve
 
-_helm="helm --tiller-namespace concourse"
+_helm="helm --kube-context=${_kctx} --tiller-namespace concourse"
 
 $_helm init --service-account tiller
 
